#!/usr/bin/perl
use 5.010;
use Encode qw(decode_utf8);

$format = shift @ARGV;
$args = '';
$args = join(', ', @ARGV) if ($#ARGV + 1);
$args = ", $args" if ($#ARGV + 1);

&dogeneric;

sub dogeneric
{
	my $name = "srcs/generic";

	&execute ("cp ${name}.c ${name}.c.bak");
	open(BAK, "<${name}.c.bak");
	open(FILE, ">${name}.c");
	while (<BAK>) {
		s/__FORMAT__/$format/;
		s/__ARGS__/$args/;
		print FILE;
	}

	close BAK;
	close FILE;

	&execute ("make -C ft_printf >/dev/null");
	&execute ("gcc -Wno-overflow -o ft_printf_main ${name}.c -Ift_printf/includes -Lft_printf -lftprintf");
	&execute ("mv ${name}.c.bak ${name}.c");
}
sub execute
{
	my $cmd = shift;
#	say "\$> $cmd";
	system $cmd;
}
