#!/usr/bin/perl
use 5.010;

$format = shift @ARGV;
$args = join(', ', @ARGV);

&dogeneric;

sub dogeneric
{
	my $gen = "generic";

	system ("cp ${gen}.c ${gen}.c.bak");
	open(BAK, "<${gen}.c.bak");
	open(FILE, ">${gen}.c");
	while (<BAK>) {
		s/__FORMAT__/\"$format\"/;
		s/__ARGS__/$args/;
		print FILE;
	}

	close BAK;
	close FILE;

	system ("cp ${gen}c.c ${gen}c.c.bak");
	open(BAK, "<${gen}c.c.bak");
	open(FILE, ">${gen}c.c");
	while (<BAK>) {
		s/__FORMAT__/\"$format\"/;
		s/__ARGS__/$args/;
		print FILE;
	}

	system ("gcc ${gen}.c -Ift_printf/includes -Lft_printf -lftprintf");
	system ("gcc ${gen}c.c -o ft_printf_test_correct");

	system ("mv ${gen}.c.bak ${gen}.c");
	system ("mv ${gen}c.c.bak ${gen}c.c");

	system ("./a.out && rm a.out");
}

